from os import environ

#TELEGRAM_API_URL = "https://api.telegram.org/bot{}/{}"
#TELEGRAM_BOT_USERNAME = environ["TELEGRAM_BOT_USERNAME"]
TELEGRAM_SECRET_URL = environ["TELEGRAM_TOKEN"]#in origine doveva essere _HOOK
TELEGRAM_TOKEN = environ["TELEGRAM_TOKEN"]
OPENSHIFT_GEAR_DNS = environ["OPENSHIFT_GEAR_DNS"]
OPENSHIFT_REPO_DIR = environ["OPENSHIFT_REPO_DIR"]
OPENSHIFT_PYTHON_IP = environ["OPENSHIFT_PYTHON_IP"]
OPENSHIFT_PYTHON_PORT = environ["OPENSHIFT_PYTHON_PORT"]
TELEGRAM_URL_HOOK = 'https://{}/{}'.format(OPENSHIFT_GEAR_DNS,TELEGRAM_TOKEN)